### ISSUE TITLE
Create a conda package

### ISSUE THREAD

**Issue by Chilipp** [ClimateClara/arc3o#2]
As this package depends on libraries like numpy, matplotlib, etc., I strongly recommend to create a conda package as this provides better tools for installation and distribution than the default python packaging system. But to work on this, we need to wait until #1 is finished, so we'll come back later.

- [x] #1 finished

**Comment by ClimateClara** [comment]
I have been researching a little if I could do this without your help but the variety of information is too overwhelming. Can you point to which documentation I should follow, whenever you have time? :)

**Comment by Chilipp** [comment]
Depends a bit on what you want. Do you just want to put it on conda-forge? Or do you want your own channel? The latter only makes sense I guess if you want to use it for CI

**Comment by ClimateClara** [comment]
Hmmm, again I don't know much about all this. I would start with the easiest, which is probably conda-forge? And then I'll see how much more effort I want to put into this. Can we move it to my own channel if I decide to use it for CI?

**Comment by Chilipp** [comment]
yes, conda-forge would be the easiest. We can add a recipe to this repository if you want to use it for CI. I do this for my packages, and then call the tests when building the conda recipe (see [this CI config](https://github.com/psyplot/psy-view/blob/master/.travis.yml) for instance. but unfortunately there is no guide yet how to do this (I did want to develop one for [SORSE](https://pad.gwdg.de/RsfrADceRp2dc_myoTy9hw?both#), but did not had time for it yet.

Anyway, for conda-forge, you first have to publish your package to https://pypi.org/. And then you submit a PR to the [staged-recipes](https://github.com/conda-forge/staged-recipes) repository with your new conda build recipe. Do you need help with that?

**Comment by Chilipp** [comment]
uploading packages on pypi.org is quite simple. 

1. Just install `twine` (`conda install twine` for instance),
2. run `python setup.py sdist` in your repository root
3. create an account on pypi.org
4. upload your package by running `twine upload dist/arc3o*.tar.gz` at your repository root

**Comment by ClimateClara** [comment]
Thanks I'll have a try then! Probably I'll know then if I need help: At least there is some documentation I can scan through first! :)

**Comment by ClimateClara** [comment]
Hey @Chilipp ! Thanks for everything!! Everything worked and arc3o is now on conda-forge! 👍

**Comment by Chilipp** [comment]
awesome! This was really fast :smiley:

**Comment by ClimateClara** [comment]
I really owe it to your patient guidance!
