### ISSUE TITLE
Generate the docs with sphinx

### ISSUE THREAD

**Issue by Chilipp** [ClimateClara/arc3o#4]
Ultimatively you want to have your package documentation automatically generated from your code. Sphinx is a great tool for this and you can publish it for free using readthedocs.org. You should have finished #1 before your work on this.

- [x] #1 finished

 To do this,

1. Make a `docs` folder
2. [get started with sphinx-quickstart](https://www.sphinx-doc.org/en/master/usage/quickstart.html) and adapt your `index.rst` file
3. include [autodoc](https://www.sphinx-doc.org/en/master/usage/quickstart.html#autodoc) and [intersphinx-mapping](https://www.sphinx-doc.org/en/master/usage/quickstart.html#intersphinx) in your `conf.py` script
4. Automatically generate the api-documentation using [sphinx-autogen](https://www.sphinx-doc.org/en/master/man/sphinx-autogen.html)
5. Include the API reference file in the `toctree` of your `index.rst` file.
6. build the docs running `make html` in your `docs` folder
7. If #3 is still open, you will get a lot of warnings as sphinx does not understand your docstrings. Nevertheless, you should get a that you can open with firefox at `docs/_build/html/index.html`

**Comment by Chilipp** [comment]
The current [manual](../blob/master/Manual_ARC3O.pdf) should then be removed and the necessary content should be included in some of the restructured text files

**Comment by ClimateClara** [comment]
Should I open a new branch for this or can this be done in the same branch as rewriting the in-line documentation (see Issue #3 )?

**Comment by Chilipp** [comment]
I think we can do it in the same branch and then make on PR that closes both issues

**Comment by ClimateClara** [comment]
Looks good to me: https://arc3o.readthedocs.io/en/latest/index.html
